import undefined from './skills/Responsibility for One's Behavior.skill.json';
import undefined from './skills/Strategic Planning Framework Phases Application.skill.json';
import undefined from './skills/Innovative Process Initiative Assessment.skill.json';
import undefined from './skills/Innovation Workshop Facilitation.skill.json';
import undefined from './skills/Policies and Procedures Assessment.skill.json';
import undefined from './skills/Strategic Planning Workshop Leadership.skill.json';
import undefined from './skills/New Technology Implementation.skill.json';
import undefined from './skills/Social Media Channel Management.skill.json';
import undefined from './skills/Social Media Post Scheduling.skill.json';
import undefined from './skills/Moderate Social Media Conversation.skill.json';
import undefined from './skills/Clear Communication.skill.json';
import undefined from './skills/Employee Sharing Opportunities Provision.skill.json';
import undefined from './skills/Ethical Violation Investigation.skill.json';
import undefined from './skills/Governing Bodies Collaboration.skill.json';
import undefined from './skills/Goals Communication Development.skill.json';
import undefined from './skills/Complaint Response System Development.skill.json';
import undefined from './skills/Communications Metrics Development.skill.json';
import undefined from './skills/Legal Compliance Training Development.skill.json';
import undefined from './skills/Research Results Conclusion.skill.json';
import undefined from './skills/Employee Needs Instruction.skill.json';
import undefined from './skills/Performance Strategy Workshops Leadership.skill.json';
import undefined from './skills/Organizational Strategy Training.skill.json';
import undefined from './skills/Quality of Care Improvement Motivation.skill.json';
import undefined from './skills/Unethical Conduct Reason Investigation.skill.json';
import undefined from './skills/Team Relationship Maintenance.skill.json';
import undefined from './skills/Group Meeting Organization.skill.json';
import undefined from './skills/Motivational Employee Meeting Leadership.skill.json';
import undefined from './skills/Culture of Integrity Promotion.skill.json';
import undefined from './skills/Project Report Preparation.skill.json';
import undefined from './skills/Workplace Relationship Research.skill.json';
import undefined from './skills/Public Data Organizing.skill.json';
import undefined from './skills/Common Objective Collaboration.skill.json';
import undefined from './skills/Company Communications Edits for Audiences.skill.json';
import undefined from './skills/Company Communications Editing.skill.json';
import undefined from './skills/Communications Review Management.skill.json';
import undefined from './skills/Ethical Guidelines Development.skill.json';
import undefined from './skills/Corporate Ethics Instruction.skill.json';
import undefined from './skills/Ethics Violation Reporting Process Implementation.skill.json';
import undefined from './skills/Perform Analysis.skill.json';
import undefined from './skills/Organizational Code of Conduct Development.skill.json';
import undefined from './skills/Goals Achievement Communication Development.skill.json';
import undefined from './skills/Communications Program Improvement Implementation.skill.json';
import undefined from './skills/Ethical Obligation Training Development.skill.json';
import undefined from './skills/Employee Praise Instruction.skill.json';
import undefined from './skills/Verbal Negotiations Instruction.skill.json';
import undefined from './skills/Organizational Strategy Selection.skill.json';
import undefined from './skills/Ethical Behavior Demonstration.skill.json';
import undefined from './skills/Public Data Analysis.skill.json';
import undefined from './skills/Communications Distribution Management.skill.json';
import undefined from './skills/Streamline Processes by Using Time Effectively.skill.json';
import undefined from './skills/Develop a Compressive Plan for Managing Time.skill.json';
import undefined from './skills/Assess Time Management Practices.skill.json';
import undefined from './skills/Make Time Management a Priority.skill.json';
import undefined from './skills/Apply Time Management Techniques.skill.json';
import undefined from './skills/Assess Critical Thinking Skills.skill.json';
import undefined from './skills/Apply Logic and Reasoning Techniques.skill.json';
import undefined from './skills/Make Judgements for Work Challenges.skill.json';
import undefined from './skills/Assess a Planned Problem-Solving Solution.skill.json';
import undefined from './skills/Develop Ideas to Solve Problems.skill.json';
import undefined from './skills/Analyze the Need for Active Listening in Various Situations.skill.json';
import undefined from './skills/Display Attitude and Belief Awareness.skill.json';
import undefined from './skills/Account Balances Adjustment.skill.json';
import undefined from './skills/Account Balances Presentation.skill.json';
import undefined from './skills/Reconciliation Schedules Preparation.skill.json';
import undefined from './skills/Economic Movement Analysis.skill.json';
import undefined from './skills/Economic Status Communication.skill.json';
import undefined from './skills/Financial Reviews Conduction.skill.json';
import undefined from './skills/Full Cycle Financial Accounting.skill.json';
import undefined from './skills/Financial Best Practices Implementation.skill.json';
import undefined from './skills/Accounting Operations Leadership.skill.json';
import undefined from './skills/Day-to-Day Recording.skill.json';
import undefined from './skills/Financial Report Preparation.skill.json';
import undefined from './skills/Financial Statement Preparation for Accounting.skill.json';
import undefined from './skills/Accounting Trend Analysis.skill.json';
import undefined from './skills/Company-Wide Plan Development.skill.json';
import undefined from './skills/Financial Statement Review.skill.json';
import undefined from './skills/Basic Accounting Process Identification.skill.json';
import undefined from './skills/Month-End Close Execution.skill.json';
import undefined from './skills/Relevant Information Collection.skill.json';
import undefined from './skills/Information Analysis.skill.json';
import undefined from './skills/Fact Analysis.skill.json';
import undefined from './skills/Financial Position Determination.skill.json';
import undefined from './skills/Cost-Benefit Analysis.skill.json';
import undefined from './skills/Budget Summary and Recommendations.skill.json';
import undefined from './skills/Transaction Evaluation.skill.json';
import undefined from './skills/Double Entry Accounting Operation.skill.json';
import undefined from './skills/Journal Entry Creation.skill.json';
import undefined from './skills/General Ledger Information Recording.skill.json';
import undefined from './skills/Annual Operating Budget Formulation.skill.json';
import undefined from './skills/Preparation.skill.json';
import undefined from './skills/New Product Development.skill.json';
import undefined from './skills/Violation Investigation.skill.json';
import undefined from './skills/Complaint Response System Development.skill.json';
import undefined from './skills/Compliance Training Plan Development.skill.json';
import undefined from './skills/Unethical Conduct Investigation.skill.json';
import undefined from './skills/Legal Protection.skill.json';
import undefined from './skills/Employee Education.skill.json';
import undefined from './skills/Third Party Reporting Process Implementation.skill.json';
import undefined from './skills/Code Modification.skill.json';
import undefined from './skills/SWOT (strengths, weaknesses, opportunities, and threats) Analysis.skill.json';
import undefined from './skills/Case Management Application.skill.json';
import undefined from './skills/Case Management Referral Process Implementation.skill.json';
import undefined from './skills/Service Barrier Strategy.skill.json';
import undefined from './skills/Client Outcome Evaluation.skill.json';
import undefined from './skills/Cash Flow Analysis Liquidity.skill.json';
import undefined from './skills/Cash Flow Statement Completion.skill.json';
import undefined from './skills/Cash Flow Statement Verification.skill.json';
import undefined from './skills/Change Management Technique Application.skill.json';
import undefined from './skills/Customized Lending Package Implementation.skill.json';
import undefined from './skills/Commercial Credit Portfolio Management.skill.json';
import undefined from './skills/Commercial Credit Portfolio Application.skill.json';
import undefined from './skills/Help Community Management of Corporate Social Media.skill.json';
import undefined from './skills/Community Management Assistance Post Scheduling.skill.json';
import undefined from './skills/Help With Social Media Moderation.skill.json';
import undefined from './skills/Target Audience Message Communication.skill.json';
import undefined from './skills/Engaging and Reliable Message Communication.skill.json';
import undefined from './skills/Process Improvement Plan Creation.skill.json';
import undefined from './skills/Teammate Role, Behavior, and Skill Identification.skill.json';
import undefined from './skills/Work With Others.skill.json';
import undefined from './skills/Consolidated Balance Sheet Analysis Schedule Creation.skill.json';
import undefined from './skills/Consolidated Balance Sheet Analysis Schedule Maintenance.skill.json';
import undefined from './skills/Corporate Accounting Function Execution.skill.json';
import undefined from './skills/Cost Classification Application.skill.json';
import undefined from './skills/Conduct Variance Analysis.skill.json';
import undefined from './skills/Standard Cost Model and Overhead Allocation Development.skill.json';
import undefined from './skills/Standard Cost Model and Overhead Allocation Response.skill.json';
import undefined from './skills/Monthly Variance Analysis and Explanation Provisioning.skill.json';
import undefined from './skills/Job Cost Recording.skill.json';
import undefined from './skills/Job Report and Transaction Statement Reconciliation.skill.json';
import undefined from './skills/Production Level Cost Behavior Identification.skill.json';
import undefined from './skills/Attitude and Belief Awareness Demonstration.skill.json';
import undefined from './skills/Assumption and Bias Awareness Demonstration.skill.json';
import undefined from './skills/Customer Interaction Channel Analysis.skill.json';
import undefined from './skills/Data Collection Rule Development.skill.json';
import undefined from './skills/Use Methods for Data Collection.skill.json';
import undefined from './skills/Decision-Making Process Effectiveness Evaluation.skill.json';
import undefined from './skills/Work Approach Acceptance.skill.json';
import undefined from './skills/Effective Economic Operation Determination.skill.json';
import undefined from './skills/Economic Behavior Interpretation.skill.json';
import undefined from './skills/Macroeconomic Development Analysis.skill.json';
import undefined from './skills/Economic Principle Application.skill.json';
import undefined from './skills/Macroeconomics Principles Application.skill.json';
import undefined from './skills/Economic Business Factor Impact Analysis.skill.json';
import undefined from './skills/Income Statement Trend Analysis.skill.json';
import undefined from './skills/Balance Sheet Reconciliation.skill.json';
import undefined from './skills/Balance Sheet Maintenance.skill.json';
import undefined from './skills/Structured Environment Financial Records.skill.json';
import undefined from './skills/Financial Health Evaluation.skill.json';
import undefined from './skills/Financial Forecasts Preparation.skill.json';
import undefined from './skills/Financial Accounting Standards Board (FASB) Documentation Communication.skill.json';
import undefined from './skills/Forecast, Report, and Analysis Preparation.skill.json';
import undefined from './skills/Financial Statements Data Compilation.skill.json';
import undefined from './skills/Financial Statement Analysis.skill.json';
import undefined from './skills/Balance Sheet and Income Statement Financial Statements Creation.skill.json';
import undefined from './skills/Comprehensive Financial Statements Creation.skill.json';
import undefined from './skills/Financial Statements Interpretation.skill.json';
import undefined from './skills/Monthly and Quarterly Financial Statements Preparation.skill.json';
import undefined from './skills/Monthly and Quarterly Financial Statements Analysis.skill.json';
import undefined from './skills/Compiled Data Analysis.skill.json';
import undefined from './skills/Statement of Financial Position.skill.json';
import undefined from './skills/Asset, Liability, and Capital Account Entries Preparation.skill.json';
import undefined from './skills/Current Financial Status Reporting.skill.json';
import undefined from './skills/Accounting Software Application.skill.json';
import undefined from './skills/Accounting Standards Codification (ASC) Standards Application.skill.json';
import undefined from './skills/Day-to-Day Accounting Procedure Execution.skill.json';
import undefined from './skills/Accounting Standards Codification (ASC) Standards Identification.skill.json';
import undefined from './skills/Entity Applicability or Exemption Identification.skill.json';
import undefined from './skills/Ensure Complete Financial Statements.skill.json';
import undefined from './skills/Senior Managers Organizational Policy Advisement.skill.json';
import undefined from './skills/Senior Managers Organizational Policy Recommendation.skill.json';
import undefined from './skills/Record-Keeping Procedures Development.skill.json';
import undefined from './skills/Technology Implementation Assistance.skill.json';
import undefined from './skills/International Business Issues Recognition.skill.json';
import undefined from './skills/Organizational Structure Implementation.skill.json';
import undefined from './skills/Organizational Structures Recognition.skill.json';
import undefined from './skills/Behavior Modification Help.skill.json';
import undefined from './skills/Job Data Provision.skill.json';
import undefined from './skills/Employee Performance Review.skill.json';
import undefined from './skills/Company Performance Reports Analysis.skill.json';
import undefined from './skills/Specific, Measurable, Achievable, Relevant, Time-Bound (SMART) Goals Creation.skill.json';
import undefined from './skills/Financial Principles Application.skill.json';
import undefined from './skills/Accounting Problem Information Collection.skill.json';
import undefined from './skills/Fundamental Accounting Equation Problem Resolution.skill.json';
import undefined from './skills/Procurement Audit Framework Creation State Supply Commission Act 1991.skill.json';
import undefined from './skills/Solution Approximation.skill.json';
import undefined from './skills/Mathematical Concepts.skill.json';
import undefined from './skills/Problem Solving with Mathematical Techniques.skill.json';
import undefined from './skills/Determine Mathematical Analysis.skill.json';
import undefined from './skills/Summarize Data.skill.json';
import undefined from './skills/Mathematical Model Implementation.skill.json';
import undefined from './skills/Judgment Determination.skill.json';
import undefined from './skills/Report Assistance.skill.json';
import undefined from './skills/Predictive Data Sorting.skill.json';
import undefined from './skills/Risk Areas Assessment.skill.json';
import undefined from './skills/Risk Mitigation Plans Evaluation.skill.json';
import undefined from './skills/Risk Management Policy Advice.skill.json';
import undefined from './skills/Data Security Policies Communication.skill.json';
import undefined from './skills/Financial Valuation Recommendations.skill.json';
import undefined from './skills/Team Member Communication.skill.json';
import undefined from './skills/Workplace Relationship Application.skill.json';
import undefined from './skills/Complex Spreadsheet Tasks Completion.skill.json';
import undefined from './skills/Spreadsheet Tasks Completion.skill.json';
import undefined from './skills/Advanced Charts Creation.skill.json';
import undefined from './skills/Advanced Spreadsheets Design.skill.json';
import undefined from './skills/Business Operations Planning.skill.json';
import undefined from './skills/Spreadsheet Data Sorting.skill.json';
import undefined from './skills/Outlier Identification.skill.json';
import undefined from './skills/Facilitation Assistance.skill.json';
import undefined from './skills/Communication Plan.skill.json';
import undefined from './skills/Strategic Planning Facilitation.skill.json';
import undefined from './skills/Workshop for Managers Facilitation.skill.json';
import undefined from './skills/Develop a Tax Compliance Detection Program.skill.json';
import undefined from './skills/Tax Data Analysis.skill.json';
import undefined from './skills/Tax Research.skill.json';
import undefined from './skills/Tax Preparation Activities Coordination.skill.json';
import undefined from './skills/Tax Returns Preparation.skill.json';
import undefined from './skills/Prepare Tax Forms.skill.json';
import undefined from './skills/Conduct Quantitative Investigation.skill.json';
import undefined from './skills/Produce Behavior Variance Interpretation Statement.skill.json';
import undefined from './skills/Rapport Building Communication.skill.json';
import undefined from './skills/Meeting Engagement.skill.json';
import undefined from './skills/Manager Training Facilitation.skill.json';
import undefined from './skills/Group Meeting Conduction.skill.json';
import undefined from './skills/Budget Preparation Review.skill.json';
import undefined from './skills/Determine Decision Information.skill.json';
import undefined from './skills/Decision-Making Procedure Development.skill.json';
import undefined from './skills/Human Resource Work Completion.skill.json';
import undefined from './skills/Human Resource Project Progress Monitoring.skill.json';
import undefined from './skills/Key Project Aspects.skill.json';
import undefined from './skills/Document Validity Verification.skill.json';
import undefined from './skills/Documentation Storage.skill.json';
import undefined from './skills/Record Retention Policy.skill.json';
import undefined from './skills/Interact Via Online Video Conferencing Tools.skill.json';
import undefined from './skills/Internal Controls Procedure and Policy Development.skill.json';
import undefined from './skills/Organizational Policy Changes.skill.json';
import undefined from './skills/Budget Discrepancy Resolution.skill.json';
import undefined from './skills/Operating Budget Control.skill.json';
import undefined from './skills/Budget Preparation.skill.json';
import undefined from './skills/Project Cost Analysis.skill.json';
import undefined from './skills/Disaster Recovery Planning.skill.json';
import undefined from './skills/Prioritize Objectives.skill.json';
import undefined from './skills/Skill Enhancement.skill.json';
import undefined from './skills/Business Operation Process Creation.skill.json';
import undefined from './skills/Effectiveness Tracking.skill.json';
import undefined from './skills/Business Process Optimization.skill.json';
import undefined from './skills/Financial Health Assessment.skill.json';
import undefined from './skills/Accounting Control Completion.skill.json';
import undefined from './skills/Accounting Control Oversight.skill.json';
import undefined from './skills/Client Tax Preparation.skill.json';
import undefined from './skills/Financial Schedule Creation.skill.json';
import undefined from './skills/Tax Strategy Collaboration.skill.json';
import undefined from './skills/U.S. Securities and Exchange Commission (SEC) Compliance Forms.skill.json';
import undefined from './skills/Delinquent Accounts Inquiry.skill.json';
import undefined from './skills/Lien Removal.skill.json';
import undefined from './skills/Unpaid Debt Collection.skill.json';
import undefined from './skills/Accounting Systems Inspection.skill.json';
import undefined from './skills/Financial Information Review.skill.json';
import undefined from './skills/Financial Records Inspection.skill.json';
import undefined from './skills/Internal Financial Reporting Audit.skill.json';
import undefined from './skills/Banking Regulations Remediation Plan.skill.json';
import undefined from './skills/Substantive Testing Performance.skill.json';
import undefined from './skills/Economic Decision Advice.skill.json';
import undefined from './skills/Economic Data Collecting.skill.json';
import undefined from './skills/Enterprise Resource Planning (ERP) General Ledger (GL) Adjustments.skill.json';
import undefined from './skills/Analyze Enterprise Resource Planning (ERP) General Ledger (GL) Entries.skill.json';
import undefined from './skills/Provide Impact Analysis.skill.json';
import undefined from './skills/Generate Trends and Forecasts from GL.skill.json';
import undefined from './skills/Lead Kaizen Events.skill.json';
import undefined from './skills/Audit Findings Communication.skill.json';
import undefined from './skills/Conduct Risk Audits.skill.json';
import undefined from './skills/Financial Data Reporting.skill.json';
import undefined from './skills/Financial Transaction Integrity Implementation.skill.json';
import undefined from './skills/Financial Data Review.skill.json';
import undefined from './skills/Financial Model Scenario Development.skill.json';
import undefined from './skills/Financial Performance Evaluation.skill.json';
import undefined from './skills/Analyze Processes and Systems for Improvements.skill.json';
import undefined from './skills/Entry Error Resolution.skill.json';
import undefined from './skills/Ledger Reconciliation.skill.json';
import undefined from './skills/Internal Process Implementation.skill.json';
import undefined from './skills/Account Reconciliation Processes.skill.json';
import undefined from './skills/Allocation Methodology Creation.skill.json';
import undefined from './skills/Allocation Methodology Reporting.skill.json';
import undefined from './skills/Corporate Lease Journal Entry Creation.skill.json';
import undefined from './skills/Corporate Lease Recognition.skill.json';
import undefined from './skills/Corporate Loan Amortization.skill.json';
import undefined from './skills/Financial Statement Contingency Adjustment.skill.json';
import undefined from './skills/Financial Statement Measurement Period Adjustment.skill.json';
import undefined from './skills/General Ledger Preparation.skill.json';
import undefined from './skills/Improvement Recommendations.skill.json';
import undefined from './skills/Interfund Activity Elimination.skill.json';
import undefined from './skills/Journal Entry Preparation.skill.json';
import undefined from './skills/Loan Amortization Schedule Creation.skill.json';
import undefined from './skills/Loan Balance Reconciliation.skill.json';
import undefined from './skills/Net Asset Goodwill Recording.skill.json';
import undefined from './skills/Net Asset Noncontrolling Interest Recording.skill.json';
import undefined from './skills/Net Asset Purchase Gain Recording.skill.json';
import undefined from './skills/Standard Procedures Development.skill.json';
import undefined from './skills/Act Responsibly.skill.json';
import undefined from './skills/Completed Work Documentation.skill.json';
import undefined from './skills/Compliance Threat Evaluation.skill.json';
import undefined from './skills/Maintain Confidentiality.skill.json';
import undefined from './skills/Ethical Business Compromise Refusal.skill.json';
import undefined from './skills/Ethical Employee Behavior.skill.json';
import undefined from './skills/Ethical Standards Compliance.skill.json';
import undefined from './skills/Fundamental Principles Compliance.skill.json';
import undefined from './skills/Laws and Regulations Compliance.skill.json';
import undefined from './skills/Maintain Audit Independence.skill.json';
import undefined from './skills/Maintain Confidentiality.skill.json';
import undefined from './skills/Maintain Professional Knowledge.skill.json';
import undefined from './skills/Obtain Taxpayer Information.skill.json';
import undefined from './skills/Professional Business Communications.skill.json';
import undefined from './skills/Professional Service Expectations.skill.json';
import undefined from './skills/Professional Standard Diligence.skill.json';
import undefined from './skills/Tax Return Standards Determination.skill.json';
import undefined from './skills/Taxing Authority Standards Compliance.skill.json';
import undefined from './skills/Report Unethical Behavior.skill.json';
import undefined from './skills/Uphold Ethical Standards.skill.json';
import undefined from './skills/Company-Wide Plan Implementation.skill.json';
import undefined from './skills/Cash Flow Analysis.skill.json';
import undefined from './skills/Assets Identification.skill.json';
import undefined from './skills/Double Entry Transactions.skill.json';
import undefined from './skills/Export Financial Transactions.skill.json';
import undefined from './skills/General Ledger Entry.skill.json';
import undefined from './skills/Stakeholder Reporting.skill.json';
import undefined from './skills/Trend Forecasting.skill.json';
import undefined from './skills/Advanced Accounting Processes.skill.json';
import undefined from './skills/Accounting Process Deployment.skill.json';
import undefined from './skills/Financial Data Uploading.skill.json';
import undefined from './skills/Financial Statement Generation.skill.json';
import undefined from './skills/General Ledger Codes Assignment.skill.json';
import undefined from './skills/Disbursement Posting.skill.json';
import undefined from './skills/Expense Report Analysis.skill.json';
import undefined from './skills/Process Invoices.skill.json';
import undefined from './skills/Maintain Vendor Files.skill.json';
import undefined from './skills/Determine Bad Debt Accounting Method.skill.json';
import undefined from './skills/Bad Debt Reserves Review.skill.json';
import undefined from './skills/Bad Debt Transactions Review.skill.json';
import undefined from './skills/Client Files Maintenance.skill.json';
import undefined from './skills/Income Report Analysis.skill.json';
import undefined from './skills/Receipt Posting.skill.json';
import undefined from './skills/Change Estimation.skill.json';
import undefined from './skills/Record Payments.skill.json';
import undefined from './skills/Record Revenues.skill.json';
import undefined from './skills/Agency Relationship Identification.skill.json';
import undefined from './skills/Agent Rights.skill.json';
import undefined from './skills/Legal Remedy Identification.skill.json';
import undefined from './skills/Liability Mitigation Strategies and Policies.skill.json';
import undefined from './skills/Financial Data Analysis for Tax Implications.skill.json';
import undefined from './skills/Audit Report Preparation.skill.json';
import undefined from './skills/Business Systems Audit.skill.json';
import undefined from './skills/Compliance Review.skill.json';
import undefined from './skills/Enrollment Accounts Reconciliation.skill.json';
import undefined from './skills/IRS Liaison.skill.json';
import undefined from './skills/Payroll Account Balancing.skill.json';
import undefined from './skills/Procedure Development.skill.json';
import undefined from './skills/Retirement Deductions Verification.skill.json';
import undefined from './skills/Stakeholder Education.skill.json';
import undefined from './skills/Inspect Business Records.skill.json';
import undefined from './skills/Tax Law Review.skill.json';
import undefined from './skills/Tax Audit Policy Design.skill.json';
import undefined from './skills/Balance Sheet Discrepancy Resolution.skill.json';
import undefined from './skills/Reconciliation Review.skill.json';
import undefined from './skills/Analysis Management.skill.json';
import undefined from './skills/Financial Statement Information Analysis.skill.json';
import undefined from './skills/Reconciliation Record Maintenance.skill.json';
import undefined from './skills/Automated Report Creation.skill.json';
import undefined from './skills/Financial Statement Preparation.skill.json';
import undefined from './skills/Financial Statement Creation.skill.json';
import undefined from './skills/Transaction Record.skill.json';
import undefined from './skills/Data-Backed Persuasive Writing.skill.json';
import undefined from './skills/Public Announcement Creation.skill.json';
import undefined from './skills/Operating System and Utility Settings Configuration.skill.json';
import undefined from './skills/Team Member Conflict Resolution.skill.json';
import undefined from './skills/Acquisition Workpaper Consolidation Preparation.skill.json';
import undefined from './skills/Acquisition Workpapers Preparation.skill.json';
import undefined from './skills/Asset and Liability Data Combining.skill.json';
import undefined from './skills/Business Combination Consideration.skill.json';
import undefined from './skills/Consolidated Statement Intercompany Profit Elimination.skill.json';
import undefined from './skills/Financial Compliance Maintenance.skill.json';
import undefined from './skills/Firm Combination Reasons.skill.json';
import undefined from './skills/Business Combination Payment Factors.skill.json';
import undefined from './skills/Journal Entry and System Reconciliation.skill.json';
import undefined from './skills/Parent Book Entry Recording.skill.json';
import undefined from './skills/Partnership Allocation Agreements.skill.json';
import undefined from './skills/Partnership Journal Entry Preparation.skill.json';
import undefined from './skills/Subsidiary Inclusion Requirements.skill.json';
import undefined from './skills/Subsidiary Investment Recording.skill.json';
import undefined from './skills/Consolidated Workpaper Preparation.skill.json';
import undefined from './skills/Workpaper Entry Elimination.skill.json';
import undefined from './skills/Business Operations Analysis.skill.json';
import undefined from './skills/Process Improvement Analysis.skill.json';
import undefined from './skills/Common Goal Identification.skill.json';
import undefined from './skills/Accounting Documentation.skill.json';
import undefined from './skills/Financial Statement Analysis.skill.json';
import undefined from './skills/Monthly Financial Statements.skill.json';
import undefined from './skills/Improvement Ideas.skill.json';
import undefined from './skills/Project Outcome Conceptualization.skill.json';
import undefined from './skills/Employee Critical Thinking Training.skill.json';
import undefined from './skills/Factual Evidence Correlation.skill.json';
import undefined from './skills/Factual Evidence for Judgment Forming.skill.json';
import undefined from './skills/Customer Account Record Management.skill.json';
import undefined from './skills/Customer Problem Resolution.skill.json';
import undefined from './skills/Customer Satisfaction.skill.json';
import undefined from './skills/Customer Base Growth.skill.json';
import undefined from './skills/Customer Inquiry Responsiveness.skill.json';
import undefined from './skills/Timely Invoicing.skill.json';
import undefined from './skills/Service Cost Communication.skill.json';
import undefined from './skills/Conduct Customer Contact Training.skill.json';
import undefined from './skills/Customer Contact Center Management.skill.json';
import undefined from './skills/Customer Contact Training Design.skill.json';
import undefined from './skills/Customer Issue Resolution.skill.json';
import undefined from './skills/Customer Relationship Management (CRM) Strategy Development.skill.json';
import undefined from './skills/Customer Relationship Management (CRM) Strategy Implementation.skill.json';
import undefined from './skills/Inbound Customer Contact Management.skill.json';
import undefined from './skills/Customer Concern Escalation.skill.json';
import undefined from './skills/Customer Interactions.skill.json';
import undefined from './skills/Customer Service Budgeting.skill.json';
import undefined from './skills/Customer Service Protocol Design.skill.json';
import undefined from './skills/Customer Service Protocol Implementation.skill.json';
import undefined from './skills/Customer Service Response Metrics Monitoring.skill.json';
import undefined from './skills/Recruiting and Training Procedures.skill.json';
import undefined from './skills/Service Agreement Level Compliance.skill.json';
import undefined from './skills/Company Financial Data Analysis.skill.json';
import undefined from './skills/Data Accuracy Validation.skill.json';
import undefined from './skills/Data Field Text Input.skill.json';
import undefined from './skills/Source Data Information Extraction.skill.json';
import undefined from './skills/Performance Feedback.skill.json';
import undefined from './skills/Policy Options Comparison.skill.json';
import undefined from './skills/Company Data Collection.skill.json';
import undefined from './skills/Financial Health Data Collection.skill.json';
import undefined from './skills/Financial Transactions Evaluation.skill.json';
import undefined from './skills/Financial Health Analysis.skill.json';
import undefined from './skills/Financial Reporting Data Collection.skill.json';
import undefined from './skills/Profitability Improvement Analysis.skill.json';
import undefined from './skills/Cost Benefit Analysis.skill.json';
import undefined from './skills/Financial Services Recommendation.skill.json';
import undefined from './skills/Financial Services Vendor Recommendation.skill.json';
import undefined from './skills/Business Financial Improvement Strategies.skill.json';
import undefined from './skills/Financial Reports Preparation.skill.json';
import undefined from './skills/Financial Statements Comparison.skill.json';
import undefined from './skills/Financial Statements Analysis.skill.json';
import undefined from './skills/Financial Statements Creation.skill.json';
import undefined from './skills/Forecasting Processes Comparison.skill.json';
import undefined from './skills/Pro Forma Financial Statement Creation.skill.json';
import undefined from './skills/Resource Allocation Decision Making.skill.json';
import undefined from './skills/U.S. Securities and Exchange Commission (SEC) Filings Procedures Implementation.skill.json';
import undefined from './skills/U.S. Securities and Exchange Commission (SEC) Filings Procedures Preparation.skill.json';
import undefined from './skills/Audit Schedules Preparation.skill.json';
import undefined from './skills/Company Audits Representation.skill.json';
import undefined from './skills/Depreciation Budgets Monitoring.skill.json';
import undefined from './skills/Ensure Internal Control Policies and Procedures Compliance.skill.json';
import undefined from './skills/Fixed Asset Subsidiary Ledger Balance Review.skill.json';
import undefined from './skills/Fixed Assets Recording.skill.json';
import undefined from './skills/Fixed-Asset Documentation Creation Support.skill.json';
import undefined from './skills/Tactical and Strategic Approaches Recommendation.skill.json';
import undefined from './skills/Trends and Innovations Assessment.skill.json';
import undefined from './skills/Trends and Innovations Monitoring.skill.json';
import undefined from './skills/Army's Business Processes Improvements Design.skill.json';
import undefined from './skills/Business Roles and Responsibilities Negotiation.skill.json';
import undefined from './skills/General Fund Enterprise Business Systems (GFEBS) Application.skill.json';
import undefined from './skills/General Fund Enterprise Business Systems (GFEBS) Enterprise Resource Planning (ERP) Solution Instance Implementation.skill.json';
import undefined from './skills/Internal Controls Implementation.skill.json';
import undefined from './skills/Accounting Controls Development.skill.json';
import undefined from './skills/Accounting Controls Implementation.skill.json';
import undefined from './skills/Annual Period Closing Entries Preparation.skill.json';
import undefined from './skills/Annual Period Closing Entries Recording.skill.json';
import undefined from './skills/Audit Procedures Development Oversight.skill.json';
import undefined from './skills/General Ledger (GL) Account Balances and Systems Comparison.skill.json';
import undefined from './skills/General Ledger (GL) Debit and Credit Balances Discrepancies Investigation.skill.json';
import undefined from './skills/General Ledger (GL) Double Entry System Operating.skill.json';
import undefined from './skills/General Ledger (GL) Expense Records Management.skill.json';
import undefined from './skills/General Ledger (GL) Reconciliation Software Implementation.skill.json';
import undefined from './skills/General Ledger (GL) Unique Account Numbers Design.skill.json';
import undefined from './skills/Internal Controls Investigation.skill.json';
import undefined from './skills/Internal Controls Research.skill.json';
import undefined from './skills/Legal Requirements Compliance Advisement.skill.json';
import undefined from './skills/Periodic Reports Generating.skill.json';
import undefined from './skills/GAAP Internal Audit Process Development.skill.json';
import undefined from './skills/Accounting and Reporting Differences Identification.skill.json';
import undefined from './skills/Internal Training Process Oversight.skill.json';
import undefined from './skills/International Financial Reporting Standards (IFRS) and U.S. Generally Accepted Accounting Principles (GAAP) Differences Impact on Financial Statements Determination.skill.json';
import undefined from './skills/Organizational Transition Roadmap Development.skill.json';
import undefined from './skills/Reconcile Accounts Payable and Receivable According to Generally Accepted Accounting Principles (GAAP).skill.json';
import undefined from './skills/Market Analysis Development.skill.json';
import undefined from './skills/Models-Based Sector Trends Development.skill.json';
import undefined from './skills/Organizational Competitive Advantage Leadership.skill.json';
import undefined from './skills/Quantitative and Qualitative Analysis Conducting.skill.json';
import undefined from './skills/Technology Solutions Delivery Collaboration.skill.json';
import undefined from './skills/Assurance and Consulting Differences Interpretation.skill.json';
import undefined from './skills/Audit Activity Impairments Identification.skill.json';
import undefined from './skills/Audit Activity Organizational Independence Interpretation.skill.json';
import undefined from './skills/Audit Activity Skills and Competencies Identification.skill.json';
import undefined from './skills/Audit Activity Skills and Competencies Recognition.skill.json';
import undefined from './skills/Audit Knowledge and Competencies Demonstration.skill.json';
import undefined from './skills/Auditor Competency Demonstration.skill.json';
import undefined from './skills/Auditor Objectivity Assessment.skill.json';
import undefined from './skills/Auditor Objectivity Maintenance.skill.json';
import undefined from './skills/Business Systems Independent Review Provision.skill.json';
import undefined from './skills/Computer-Assisted Audit Techniques Identification.skill.json';
import undefined from './skills/Conformance Versus Nonconformance Disclosure Identification.skill.json';
import undefined from './skills/Due Professional Care Demonstration.skill.json';
import undefined from './skills/Institute of Internal Auditors (IIA) Code of Ethics Conformance Demonstration.skill.json';
import undefined from './skills/Internal Audits Reports Preparation.skill.json';
import undefined from './skills/Manual Auditing Procedures Identification.skill.json';
import undefined from './skills/Analyze Policies Promoting Objectivity.skill.json';
import undefined from './skills/Risk Reports Preparation.skill.json';
import undefined from './skills/Develop a Capacity Management Plan.skill.json';
import undefined from './skills/Information Assets Inventory Development.skill.json';
import undefined from './skills/Service Management System Implementation.skill.json';
import undefined from './skills/Conduct Payroll Processing.skill.json';
import undefined from './skills/Payroll Department Restructuring.skill.json';
import undefined from './skills/Payroll Records Best Practices Recommendation.skill.json';
import undefined from './skills/Payroll Software Implementation Coordination.skill.json';
import undefined from './skills/Payroll Software Implementation Support.skill.json';
import undefined from './skills/Ensure Presentation Consistency.skill.json';
import undefined from './skills/Presentation Preparation.skill.json';
import undefined from './skills/Presentations Delivery Rehearsal.skill.json';
import undefined from './skills/Presentations Timing Rehearsal.skill.json';
import undefined from './skills/Targeted Presentation Delivery.skill.json';
import undefined from './skills/Virtual Audience Presentation Delivery.skill.json';
import undefined from './skills/Assets Maintenance Recommendation.skill.json';
import undefined from './skills/Maintenance Plans Development.skill.json';
import undefined from './skills/Maintenance Plans Implementation.skill.json';
import undefined from './skills/Maintenance Software Implementation.skill.json';
import undefined from './skills/Project Planning Leadership.skill.json';
import undefined from './skills/Creative Problem Solving (CPS) Learner Model Application.skill.json';
import undefined from './skills/Increase Accounting Understanding.skill.json';
import undefined from './skills/Organizational Issues Resolution.skill.json';
import undefined from './skills/Proactive Technique Design.skill.json';
import undefined from './skills/Proactive Technique Implementation.skill.json';
import undefined from './skills/Problem Mitigation Planning.skill.json';
import undefined from './skills/Problem Solving Workshops Facilitation.skill.json';
import undefined from './skills/Solutions Evaluation.skill.json';
import undefined from './skills/Six Sigma Implementation.skill.json';
import undefined from './skills/Work Instructions Development.skill.json';
import undefined from './skills/Financial Analysis.skill.json';
import undefined from './skills/Procurement Compliance Requirements Development.skill.json';
import undefined from './skills/Procurement Policy Implementation.skill.json';
import undefined from './skills/Review Property Reports.skill.json';
import undefined from './skills/Property Tax Assessments Analysis.skill.json';
import undefined from './skills/Provide Tax Assessment Quality Control.skill.json';
import undefined from './skills/Tax Audits Oversight.skill.json';
import undefined from './skills/Laws Implementation Analysis.skill.json';
import undefined from './skills/Laws Implementation Monitoring.skill.json';
import undefined from './skills/Prepare Reports of Policy and Legislative Proposals.skill.json';
import undefined from './skills/Logistics Coordination.skill.json';
import undefined from './skills/Compile Operational Account Information.skill.json';
import undefined from './skills/Prepare External Compliance Audits.skill.json';
import undefined from './skills/Compliance Monitoring.skill.json';
import undefined from './skills/Compliance Program Testing Participation.skill.json';
import undefined from './skills/Regulatory Interpretation Discussion.skill.json';
import undefined from './skills/Inspection Schedule Design.skill.json';
import undefined from './skills/Serve as Privacy Risks Subject Matter Expert (SME).skill.json';
import undefined from './skills/Arrange Data into Tables.skill.json';
import undefined from './skills/Data Normalization.skill.json';
import undefined from './skills/Accounting Issues Research.skill.json';
import undefined from './skills/Reperform Substantive Testing.skill.json';
import undefined from './skills/Test Financial Assumptions with Data.skill.json';
import undefined from './skills/Present Research Findings.skill.json';
import undefined from './skills/Research Requests Resolution.skill.json';
import undefined from './skills/Risk Control Recommendation.skill.json';
import undefined from './skills/Asset Risks Identification.skill.json';
import undefined from './skills/Produce Process Assessment Reports.skill.json';
import undefined from './skills/Risk Management Reporting Tools Delivery.skill.json';
import undefined from './skills/Risk Reporting Framework Development.skill.json';
import undefined from './skills/Risk Reporting Strategy Development.skill.json';
import undefined from './skills/Risks Quantification.skill.json';
import undefined from './skills/Risk Severity Minimization.skill.json';
import undefined from './skills/Risk Transfer Determination.skill.json';
import undefined from './skills/Sales Contract Drafting.skill.json';
import undefined from './skills/Sales Contract Parties Identification.skill.json';
import undefined from './skills/List Performance Obligations.skill.json';
import undefined from './skills/Sarbanes-Oxley Act (SOX) Compliance Deficiencies Tracking.skill.json';
import undefined from './skills/Sarbanes-Oxley Act (SOX) Compliance Monitoring.skill.json';
import undefined from './skills/Sarbanes-Oxley Act (SOX) Training Provision.skill.json';
import undefined from './skills/Management System Implementation for Scheduling.skill.json';
import undefined from './skills/Accounting Schedules Report Creation.skill.json';
import undefined from './skills/Budget Alignment.skill.json';
import undefined from './skills/Budget Preparation.skill.json';
import undefined from './skills/Control Policies Compliance Collaboration.skill.json';
import undefined from './skills/Maintain a Scheduling Database.skill.json';
import undefined from './skills/Executive Calendars Management.skill.json';
import undefined from './skills/Management System Development for Scheduling.skill.json';
import undefined from './skills/Milestones Schedule Coordination.skill.json';
import undefined from './skills/Equities Analysis.skill.json';
import undefined from './skills/Mortgage-Backed Bond Analysis.skill.json';
import undefined from './skills/Mortgage-Backed Securities Reconciliation.skill.json';
import undefined from './skills/Standard Operating Procedure (SOP) Implementation.skill.json';
import undefined from './skills/Dispute Resolution.skill.json';
import undefined from './skills/Nonverbal Cues Interpretation.skill.json';
import undefined from './skills/Social Situations Navigation.skill.json';
import undefined from './skills/Data Filtering.skill.json';
import undefined from './skills/Data Sets Comparison.skill.json';
import undefined from './skills/Customer Data Collection.skill.json';
import undefined from './skills/Statistical Methods Application.skill.json';
import undefined from './skills/Create Insightful Visualizations.skill.json';
import undefined from './skills/Active Listening Demonstration.skill.json';
import undefined from './skills/Clear Message Delivery.skill.json';
import undefined from './skills/Communication Methods Deployment.skill.json';
import undefined from './skills/Communication Technique Selection.skill.json';
import undefined from './skills/Confident Speaking.skill.json';
import undefined from './skills/Search Structured Query Language (SQL) Queries Creation.skill.json';
import undefined from './skills/Structured Query Language (SQL) Query Creation.skill.json';
import undefined from './skills/Relational Databases Data Management.skill.json';
import undefined from './skills/Analyzed Problem Solution Implementation.skill.json';
import undefined from './skills/Custom Queries Design Oversight.skill.json';
import undefined from './skills/Fact Pattern Analysis.skill.json';
import undefined from './skills/Data Manipulation.skill.json';
import undefined from './skills/Problem Severity Assessment.skill.json';
import undefined from './skills/Maintenance Plans Execution Monitoring.skill.json';
import undefined from './skills/Critical Thinking Writing.skill.json';
import undefined from './skills/Liability Risks Elements Identification.skill.json';
import undefined from './skills/Risk-Avoidance Policies Development.skill.json';
import undefined from './skills/Root Cause Analysis (RCA) Process Implementation.skill.json';
import undefined from './skills/Risk Framework Development.skill.json';
import undefined from './skills/Risk Framework Implementation.skill.json';
import undefined from './skills/Liability Reporting Process Establishment.skill.json';
import undefined from './skills/Risk-Based Actions Recommendation.skill.json';
import undefined from './skills/Policies Creation.skill.json';
import undefined from './skills/Perform Report Data Analysis.skill.json';
import undefined from './skills/Data Analysis Findings Presentation.skill.json';
import undefined from './skills/Query Running.skill.json';
import undefined from './skills/Perform Cost Analysis.skill.json';
import undefined from './skills/Actual Variance Reporting.skill.json';
import undefined from './skills/Recurring Income Generation.skill.json';
import undefined from './skills/Ethics Board Conferral.skill.json';
import undefined from './skills/Risk Action Planning.skill.json';
import undefined from './skills/ARCHIVED - Effective Information Gathering.skill.json';
import undefined from './skills/Public Data Validation.skill.json';
import undefined from './skills/Information Recording.skill.json';
import undefined from './skills/Data Category Organization.skill.json';
import undefined from './skills/Identify Tort-Based Liability Risk.skill.json';
import undefined from './skills/Develop Mitigation Strategies.skill.json';
import undefined from './skills/Determine Scope Risks.skill.json';
import undefined from './skills/Data Classification.skill.json';
import undefined from './skills/Ensure Information Privacy Compliance.skill.json';
import undefined from './skills/Ensure Compliance.skill.json';
import undefined from './skills/Responsibility Acceptance.skill.json';
import undefined from './skills/Ethical Principle Application.skill.json';
import undefined from './skills/Take Ownership of Repercussions.skill.json';
import undefined from './skills/Ethical Action Leadership.skill.json';
import undefined from './skills/Risk Assessment Primer Creation.skill.json';
import undefined from './skills/Risk Minimization.skill.json';
import undefined from './skills/Perform Risk Assessments.skill.json';
import undefined from './skills/Communicate Risk Assessments Findings.skill.json';
import undefined from './skills/Organization Liability Requirement Identification.skill.json';
import undefined from './skills/Resources Use Analysis.skill.json';
import undefined from './skills/Policy and Procedure Strength Assessment.skill.json';
import undefined from './skills/Policy Options Identification.skill.json';
import undefined from './skills/Public Issues Evaluation.skill.json';
import undefined from './skills/Socioeconomic Impact Study.skill.json';
import undefined from './skills/Presentation Issues Resolution.skill.json';
import undefined from './skills/Research Findings Communication.skill.json';
import undefined from './skills/Visual Content Creation.skill.json';
import undefined from './skills/Novel Solutions.skill.json';
import undefined from './skills/Challenge Identification.skill.json';
import undefined from './skills/Frame a Problem.skill.json';
import undefined from './skills/Research-Based Decision Making.skill.json';
import undefined from './skills/Data Summary Tools.skill.json';
import undefined from './skills/Conduct Economic Research.skill.json';
import undefined from './skills/Risk Resolution Coordination.skill.json';
import undefined from './skills/Exposure Submission Preparation.skill.json';
import undefined from './skills/Business Current State Data Analysis.skill.json';
import undefined from './skills/Add Complex Formulas.skill.json';
import undefined from './skills/Add Simple Formulas.skill.json';
import undefined from './skills/Basic Spreadsheet Tasks.skill.json';
import undefined from './skills/Simple Spreadsheet Calculations.skill.json';
import undefined from './skills/Complex Business Models.skill.json';
import undefined from './skills/Data Import.skill.json';
import undefined from './skills/Enter Financial Information.skill.json';
import undefined from './skills/Perform Aggregations.skill.json';
import undefined from './skills/Spreadsheet Data Presentation.skill.json';
import undefined from './skills/Spreadsheet Forms Creation.skill.json';
import undefined from './skills/Trend Tracking.skill.json';
import undefined from './skills/Accounting Processes Oversight.skill.json';
import undefined from './skills/Direct Reports Management.skill.json';
import undefined from './skills/Senior Leadership Collaboration.skill.json';
import undefined from './skills/Probability Deduction.skill.json';
import undefined from './skills/Cox Regression Analysis.skill.json';
import undefined from './skills/Perform Linear Regression Analysis.skill.json';
import undefined from './skills/Logistic Regression Analysis.skill.json';
import undefined from './skills/Median Regression Analysis.skill.json';
import undefined from './skills/Poisson Regression Analysis.skill.json';
import undefined from './skills/Population Statistics Inference.skill.json';
import undefined from './skills/Statistical Model Selection.skill.json';
import undefined from './skills/Statistical Analysis Application.skill.json';
import undefined from './skills/Statistical Model Identification.skill.json';
import undefined from './skills/Basic Inferential Analysis.skill.json';
import undefined from './skills/Multivariate Analysis.skill.json';
import undefined from './skills/Predictive Modeling.skill.json';
import undefined from './skills/Time-Series Data Clustering.skill.json';
import undefined from './skills/Data Collection.skill.json';
import undefined from './skills/Predictive Mathematical Modeling.skill.json';
import undefined from './skills/Consultation.skill.json';
import undefined from './skills/Data Collection Process.skill.json';
import undefined from './skills/Performance Strategizing.skill.json';
import undefined from './skills/Strategic Planning.skill.json';
import undefined from './skills/Business Strategy Development.skill.json';
import undefined from './skills/Business Strategy Planning.skill.json';
import undefined from './skills/Billing Regulations Implementation.skill.json';
import undefined from './skills/Billing System Management.skill.json';
import undefined from './skills/Customer Account and Balance Status Management.skill.json';
import undefined from './skills/Customer Payment Receipt.skill.json';
import undefined from './skills/Customer Payment Sorting.skill.json';
import undefined from './skills/Fraudulent Customer Billing Identification.skill.json';
import undefined from './skills/Invoice Creation.skill.json';
import undefined from './skills/Account Invoicing and Reconciliation Performance.skill.json';
import undefined from './skills/Staffing and Training Needs Forecasting.skill.json';
import undefined from './skills/Bookkeeping Accuracy Checking.skill.json';
import undefined from './skills/Accounting Errors Troubleshooting Guidelines.skill.json';
import undefined from './skills/Solutions Implementation.skill.json';
import undefined from './skills/Team Troubleshooting Skills Development.skill.json';
import undefined from './skills/Budget Adjustments Advisement.skill.json';
import undefined from './skills/High-Value Variances Investigation.skill.json';
import undefined from './skills/Improvements Identification.skill.json';
import undefined from './skills/Project Performance Deviations Investigation.skill.json';
import undefined from './skills/Annual Report Entry.skill.json';
import undefined from './skills/Annual Reports Preparation.skill.json';
import undefined from './skills/Non-Compliance Reporting Policy Development.skill.json';
import undefined from './skills/Non-Compliance Reporting Recommendations.skill.json';
import undefined from './skills/Statuary Accounting Principles (SAP) Adherence.skill.json';
import undefined from './skills/Statuary Accounting Principles (SAP) Reconciliation.skill.json';
import undefined from './skills/Statutory Accounting Principles Advisement.skill.json';
import undefined from './skills/Financial Suspicions Communication Procedures Design.skill.json';
import undefined from './skills/Financial Suspicions Communication Procedures Facilitation.skill.json';
import undefined from './skills/Suspicious Activity Report (SAR) Policies Communication.skill.json';
import undefined from './skills/Suspicious Financial Activity Reporting Process Development.skill.json';
import undefined from './skills/Suspicious Financial Activity Reporting Process Enforcement.skill.json';
import undefined from './skills/Suspicious Transactions Identification Assistance.skill.json';
import undefined from './skills/Tax Preparation Internal Audit Process Design.skill.json';
import undefined from './skills/State Tax Authority Notice Response.skill.json';
import undefined from './skills/Liaison to Auditors.skill.json';
import undefined from './skills/Tax Authority Hierarchy.skill.json';
import undefined from './skills/Client Financial Statements Review.skill.json';
import undefined from './skills/Common Tax Law Duty Summarization.skill.json';
import undefined from './skills/Common Tax Law Violation Identification.skill.json';
import undefined from './skills/Income Tax Returns Review.skill.json';
import undefined from './skills/Internal Revenue Service Regulations Recalling.skill.json';
import undefined from './skills/Privileged Communications Rules Summarization.skill.json';
import undefined from './skills/Privileged Tax Practice Communications Situations Identification.skill.json';
import undefined from './skills/Regulations Applications.skill.json';
import undefined from './skills/Sufficient Substantiation Identification.skill.json';
import undefined from './skills/Tax Accounting Strategies Evaluation.skill.json';
import undefined from './skills/Tax Provision Schedules Updating.skill.json';
import undefined from './skills/Tax Questions Assistance.skill.json';
import undefined from './skills/Tax Return Preparer Penalties Application.skill.json';
import undefined from './skills/Taxing Authority Notices Research.skill.json';
import undefined from './skills/Taxing Authority Notices Resolution.skill.json';
import undefined from './skills/Taxpayer Audit Options Identification.skill.json';
import undefined from './skills/Taxpayer Options Within Judicial Process Identification.skill.json';
import undefined from './skills/Taxpayer Penalties Calculation.skill.json';
import undefined from './skills/Business Decision Impact Determination.skill.json';
import undefined from './skills/Federal and State Audits Management.skill.json';
import undefined from './skills/Federal and State Audit Communications.skill.json';
import undefined from './skills/Perform Tax Preparation.skill.json';
import undefined from './skills/Tax Accounting Reports Training Facilitation.skill.json';
import undefined from './skills/Tax Documentation Policies Compliance.skill.json';
import undefined from './skills/Tax Issues Resolution.skill.json';
import undefined from './skills/Tax Liabilities Scrutiny.skill.json';
import undefined from './skills/Tax Regulations Changes.skill.json';
import undefined from './skills/Audit Investigations Planning.skill.json';
import undefined from './skills/Tax Compliance Audit Programs Development.skill.json';
import undefined from './skills/Tax Compliance Responsibilities Procedures Design.skill.json';
import undefined from './skills/Tax Regulations Compliance.skill.json';
import undefined from './skills/Business Tax Law Advice.skill.json';
import undefined from './skills/International Business Tax Considerations.skill.json';
import undefined from './skills/Tax Cases Outcomes Analysis.skill.json';
import undefined from './skills/Tax Consequences Advisement.skill.json';
import undefined from './skills/Tax Laws Advisement.skill.json';
import undefined from './skills/Tax Laws Interpretation.skill.json';
import undefined from './skills/Tax Ruling Advisement.skill.json';
import undefined from './skills/Cash Flow Forecasting.skill.json';
import undefined from './skills/Financial Plan Analysis.skill.json';
import undefined from './skills/Tax Estimates Monitoring.skill.json';
import undefined from './skills/Tax Estimates Review.skill.json';
import undefined from './skills/Tax Information Summarization.skill.json';
import undefined from './skills/Tax Issues Communication.skill.json';
import undefined from './skills/Tax Planning Approaches Design.skill.json';
import undefined from './skills/Tax Planning Tax Reports Preparation.skill.json';
import undefined from './skills/Tax Returns Review.skill.json';
import undefined from './skills/Accessible Tax Preparation Information.skill.json';
import undefined from './skills/Audit Process Design.skill.json';
import undefined from './skills/Client Tax Data Analysis.skill.json';
import undefined from './skills/Client Tax Returns Preparation.skill.json';
import undefined from './skills/Corporate Files Management.skill.json';
import undefined from './skills/Tax Preparation Process Advisement.skill.json';
import undefined from './skills/Tax Return Analysis.skill.json';
import undefined from './skills/Tax Developments Monitoring.skill.json';
import undefined from './skills/Tax Information Research.skill.json';
import undefined from './skills/Tax Issues Identification.skill.json';
import undefined from './skills/Tax Regulations Interpretation.skill.json';
import undefined from './skills/Financial Planning Guidance.skill.json';
import undefined from './skills/Tax Reports Preparation.skill.json';
import undefined from './skills/Tax Research Schemes Development.skill.json';
import undefined from './skills/Audit Representation.skill.json';
import undefined from './skills/Audit Settlements Negotiation.skill.json';
import undefined from './skills/Individual Tax Returns Completion.skill.json';
import undefined from './skills/Tax Law Implementation.skill.json';
import undefined from './skills/Tax Forms Completion.skill.json';
import undefined from './skills/Tax Guidelines Advisement.skill.json';
import undefined from './skills/Tax Review.skill.json';
import undefined from './skills/Tax Obligations Appeals.skill.json';
import undefined from './skills/Tax Return Data Confidentiality.skill.json';
import undefined from './skills/Tax Return Required Documents Review.skill.json';
import undefined from './skills/Tax Returns Accuracy Review.skill.json';
import undefined from './skills/Tax Returns Creation.skill.json';
import undefined from './skills/Tax Returns Substantiation.skill.json';
import undefined from './skills/Tax Strategies.skill.json';
import undefined from './skills/Taxpayer Information Collection.skill.json';
import undefined from './skills/Business Tax Returns Preparation.skill.json';
import undefined from './skills/Calculation Functions Validation.skill.json';
import undefined from './skills/Client Files Creation.skill.json';
import undefined from './skills/Financial Data Entry.skill.json';
import undefined from './skills/Financial System Implementation.skill.json';
import undefined from './skills/Tax Software Evaluation Criteria Development.skill.json';
import undefined from './skills/Tax Software Implementation.skill.json';
import undefined from './skills/Team Direction Provision.skill.json';
import undefined from './skills/Team Strengths and Weaknesses Identification.skill.json';
import undefined from './skills/Efforts Prioritization.skill.json';
import undefined from './skills/Processes Streamlining.skill.json';
import undefined from './skills/Staff Workloads Analysis.skill.json';
import undefined from './skills/Staff Workloads Prioritization.skill.json';
import undefined from './skills/Conducting Research Support.skill.json';
import undefined from './skills/Risk Evaluation.skill.json';
import undefined from './skills/Compliance Testing Execution.skill.json';
import undefined from './skills/Data Security Policies Development.skill.json';
import undefined from './skills/Data Security Policies Enforcement.skill.json';
import undefined from './skills/Financial Data Internal Controls Review.skill.json';
import undefined from './skills/Financial Data Internal Controls Debrief.skill.json';
import undefined from './skills/Financial Statements Compliance Certification.skill.json';
import undefined from './skills/Sarbanes-Oxley Act (SOX) Compliance Cases Company Representation.skill.json';
import undefined from './skills/Critical Paths Monitoring.skill.json';
import undefined from './skills/Project Plan Additional Time Inclusion.skill.json';
import undefined from './skills/Resource Scheduling Policies Creation.skill.json';
import undefined from './skills/Creative Solutions Proposal.skill.json';
import undefined from './skills/Lead Internal Employee Training.skill.json';
import undefined from './skills/Data Reporting.skill.json';
import undefined from './skills/Estimating Techniques Selection.skill.json';
import undefined from './skills/Forecast Model Application.skill.json';
import undefined from './skills/Forecasting Assumptions Validation.skill.json';
import undefined from './skills/Forecasting Trends Identification.skill.json';
import undefined from './skills/Employ Logical Process with Multiple Truths.skill.json';
import undefined from './skills/Conditional Probability Functions Employment.skill.json';
import undefined from './skills/Data Outcome Inference.skill.json';
import undefined from './skills/Patterns and Regularities Detection.skill.json';
import undefined from './skills/Chronology Set Improvement.skill.json';
import undefined from './skills/Cohesive Blocks Identification.skill.json';
import undefined from './skills/Rule-Determined Arrangement.skill.json';
import undefined from './skills/Infrastructure Budgets Development.skill.json';
import undefined from './skills/Network Systems Troubleshooting.skill.json';
import undefined from './skills/Perspective Recognition.skill.json';
import undefined from './skills/Critical Thinking Environment Fostering.skill.json';
import undefined from './skills/Information Interpretation.skill.json';
import undefined from './skills/Source Evaluation.skill.json';
import undefined from './skills/Risk Mitigation Strategy Creation.skill.json';
import undefined from './skills/Data Relationship Extraction Analysis.skill.json';
import undefined from './skills/Economic Trend Forecasting.skill.json';
import undefined from './skills/Define Economic Climate Picture.skill.json';
import undefined from './skills/Economic Theory Application.skill.json';
import undefined from './skills/Intervention Impact Value and Cost Comparison.skill.json';
import undefined from './skills/Economic Development Effort Leadership.skill.json';
import undefined from './skills/Economic Productivity Component Identification.skill.json';
import undefined from './skills/Economic Information Collection.skill.json';
import undefined from './skills/Economic Information Discrepancy Identification.skill.json';
import undefined from './skills/Economic Information Discrepancy Resolution.skill.json';
import undefined from './skills/Economic Information Solicitation.skill.json';
import undefined from './skills/Economic Report Preparation.skill.json';
import undefined from './skills/Sarbanes-Oxley Act (SOX) Compliance Determination.skill.json';
import undefined from './skills/Audit Report Writing.skill.json';
import undefined from './skills/Financial Statement Generally Accepted Accounting Principles (GAAP) Compliance Review.skill.json';
import undefined from './skills/Reconciliation Auditing.skill.json';
import undefined from './skills/Financial Statements Consolidation.skill.json';
import undefined from './skills/Generally Accepted Auditing Standards (GAAS) Compliance.skill.json';
import undefined from './skills/Financial and Regulatory Reports Preparation.skill.json';
import undefined from './skills/General Ledger (GL) Adjustments Reconciliation.skill.json';
import undefined from './skills/General Ledger (GL) Adjustments Validation.skill.json';
import undefined from './skills/Ensure Calculations and Disclosures Compliance.skill.json';
import undefined from './skills/Financial Accounting Standards Board (FASB) Citing.skill.json';
import undefined from './skills/Financial Accounting Standards Board (FASB) Enforcement.skill.json';
import undefined from './skills/Financial Accounting Standards Board (FASB) Identification.skill.json';
import undefined from './skills/Financial Accounting Standards Board (FASB) Referencing.skill.json';
import undefined from './skills/Tax Assets and Liabilities Deferment Identification.skill.json';
import undefined from './skills/Monthly Close Schedules Preparation.skill.json';
import undefined from './skills/Financial Integrity Problem Resolution.skill.json';
import undefined from './skills/Senior Leaders Advisement.skill.json';
import undefined from './skills/Financial Documents Management.skill.json';
import undefined from './skills/Financial Statements Profitability Review.skill.json';
import undefined from './skills/General Ledger Review.skill.json';
import undefined from './skills/General Ledger (GL) Reconciliation.skill.json';
import undefined from './skills/Conduct Financial Market Transactions.skill.json';
import undefined from './skills/Financial Matters Advice.skill.json';
import undefined from './skills/Industry Relationships Development.skill.json';
import undefined from './skills/Annual Financial Report Elements Identification.skill.json';
import undefined from './skills/Financial Health Improvement Guidance Procedures Design.skill.json';
import undefined from './skills/Financial Health Improvement Guidance Procedures Implementation.skill.json';
import undefined from './skills/Journal Entries Budgets Recording.skill.json';
import undefined from './skills/Journal Entries Encumbrances Recording.skill.json';
import undefined from './skills/Not-For-Profit Fiscal Condition Analysis.skill.json';
import undefined from './skills/Perform Journal Entries and Reconciliations.skill.json';
import undefined from './skills/Business Processes Development.skill.json';
import undefined from './skills/Economic Movement Process.skill.json';
import undefined from './skills/Accounting Activity Execution.skill.json';
import undefined from './skills/Accounting Activities Execution.skill.json';
import undefined from './skills/Accounting Software Solution Evaluation.skill.json';
import undefined from './skills/Accounting Software Solution Implementation.skill.json';
import undefined from './skills/Accounts Payable and Receivable Management.skill.json';
import undefined from './skills/Load Expense Files.skill.json';
import undefined from './skills/Payroll Processing.skill.json';
import undefined from './skills/Software Implementation Process Improvement.skill.json';
import undefined from './skills/Strategic Financial Decision Recommendations.skill.json';
import undefined from './skills/Accounting Systems Monitoring.skill.json';
import undefined from './skills/Design Features Development.skill.json';
import undefined from './skills/Financial Stability Assessment.skill.json';
import undefined from './skills/Function Implementation.skill.json';
import undefined from './skills/Account Analysis Oversight.skill.json';
import undefined from './skills/Enterprise-Wide Reporting Process Development.skill.json';
import undefined from './skills/Financial Adjustments Inputting.skill.json';
import undefined from './skills/Bank Transaction Analysis.skill.json';
import undefined from './skills/Culture of Compliance.skill.json';
import undefined from './skills/Enterprise-Wide Anti Money Laundering Programs.skill.json';
import undefined from './skills/System and Process Design.skill.json';
import undefined from './skills/Capital Structure Analysis.skill.json';
import undefined from './skills/Compliance Action Recommendation.skill.json';
import undefined from './skills/Financial Decision Implementation.skill.json';
import undefined from './skills/Monitor Financial Indicators.skill.json';
import undefined from './skills/Internal Process Management.skill.json';
import undefined from './skills/Plan Documentation.skill.json';
import undefined from './skills/Program Implementation.skill.json';
import undefined from './skills/Program Development.skill.json';
import undefined from './skills/Risk Assessment Process Evaluation.skill.json';
import undefined from './skills/Risk Examination.skill.json';
import undefined from './skills/Risk Identification.skill.json';
import undefined from './skills/Action Prediction.skill.json';
import undefined from './skills/Effect Documentation.skill.json';
import undefined from './skills/Human Relationship Analysis.skill.json';
import undefined from './skills/Policy Adaptation.skill.json';
import undefined from './skills/Compliance Advice.skill.json';
import undefined from './skills/Compliance Evaluation.skill.json';
import undefined from './skills/Control Implementation.skill.json';
import undefined from './skills/System Management.skill.json';
import undefined from './skills/Activity-Based Costing Budget Creation.skill.json';
import undefined from './skills/Activity-Based Costing Budget Reporting.skill.json';
import undefined from './skills/Balanced Scorecard Reporting Development.skill.json';
import undefined from './skills/Capital Budget Creation.skill.json';
import undefined from './skills/Capital Budget Reporting.skill.json';
import undefined from './skills/Zero-Based Budget Creation.skill.json';
import undefined from './skills/Zero-Based Budget Reporting.skill.json';
import undefined from './skills/Business Report Preparation.skill.json';
import undefined from './skills/Standards Implementation.skill.json';
import undefined from './skills/New Business and Business Growth Strategy Development.skill.json';
import undefined from './skills/PeopleSoft Financial Application Deployment.skill.json';
import undefined from './skills/Peoplesoft HR Guidance.skill.json';
import undefined from './skills/PeopleSoft Planning Assistance.skill.json';
import undefined from './skills/PeopleSoft Resource Planning Facilitation.skill.json';
import undefined from './skills/Recommend Cash Flow Manipulation Best Practices.skill.json';
import undefined from './skills/Corporate Strategy Creation.skill.json';
import undefined from './skills/Causal and Non-Causal Differentiation.skill.json';
import undefined from './skills/Causal Inference.skill.json';
import undefined from './skills/Causal Quantity Estimation.skill.json';
import undefined from './skills/Causation Exploration.skill.json';
import undefined from './skills/Form 8484 Violation Reporting.skill.json';
import undefined from './skills/Client Interests Protection.skill.json';
import undefined from './skills/Differentiate Misconduct Types.skill.json';
import undefined from './skills/Law Compliance.skill.json';
import undefined from './skills/Commercial Lending Review Process Determination.skill.json';
import undefined from './skills/Company Editing.skill.json';
import undefined from './skills/Company Management.skill.json';
import undefined from './skills/Information Sharing.skill.json';
import undefined from './skills/Principled Negotiation Implementation.skill.json';
import undefined from './skills/Communication and Meeting Facilitation.skill.json';
import undefined from './skills/Define Project Timelines and Dependencies.skill.json';
import undefined from './skills/Organizational Communication Facilitation.skill.json';
import undefined from './skills/Monthly Closing Journal Entry and Account Analysis Input.skill.json';
import undefined from './skills/Sarbanes-Oxley (SOX) Act and Internal Compliance Standards Preparation.skill.json';
import undefined from './skills/Business Unit Profitability Requirements Analysis.skill.json';
import undefined from './skills/Business Unit Profitability Requirements Creation.skill.json';
import undefined from './skills/Fixed Versus Variable Overhead Allocation Analysis.skill.json';
import undefined from './skills/Fixed Versus Variable Overhead Allocation Creation.skill.json';
import undefined from './skills/Transfer Pricing Methodology Creation.skill.json';
import undefined from './skills/Transfer Pricing Methodology Reporting.skill.json';
import undefined from './skills/Cost Compliance Internal Audit Process Development.skill.json';
import undefined from './skills/Devise Efficient Business Processes.skill.json';
import undefined from './skills/Idea Brainstorming.skill.json';
import undefined from './skills/Similar Situations Investigation.skill.json';
import undefined from './skills/Work-Related Issue Solution.skill.json';
import undefined from './skills/Client Monitoring Process Implementation.skill.json';
import undefined from './skills/Collateral Risk Determination Process Implementation.skill.json';
import undefined from './skills/Customer Creditworthiness and Credit Limit Determination.skill.json';
import undefined from './skills/Conduct Credit Risk Management.skill.json';
import undefined from './skills/Credit Risk Solution Implementation.skill.json';
import undefined from './skills/Internally Designed Model and Credit Scorecard Employment.skill.json';
import undefined from './skills/Lender Credit Risk Solution Implementation.skill.json';
import undefined from './skills/Accounting Software Implementation.skill.json';
import undefined from './skills/Financial Crime Evidence Detection.skill.json';
import undefined from './skills/Financial Fraud Scheme Exposure.skill.json';
import undefined from './skills/Financial Fraud Scheme Identification.skill.json';
import undefined from './skills/Financial Investigation Findings Communication.skill.json';
import undefined from './skills/Fraud Capture Program and System Creation.skill.json';
import undefined from './skills/Logic and Reasoning Strengths and Weaknesses Identification.skill.json';
import undefined from './skills/Dataset Review.skill.json';
import undefined from './skills/Data Maintenance Best Practices Development.skill.json';
import undefined from './skills/Data Visualization Program Analysis.skill.json';
import undefined from './skills/Pivot Functionality Simulation Software Selection.skill.json';
import undefined from './skills/Pivot Table Creation.skill.json';
import undefined from './skills/Conduct Records Management (RM) Annual Reviews.skill.json';
import undefined from './skills/Monthly Statistical Reporting Metrics Compilation.skill.json';
import undefined from './skills/Record Retention Policy Compliance Execution.skill.json';
import undefined from './skills/Records Management (RM) Profession Changes Review.skill.json';
import undefined from './skills/Draw Conclusions from Premises.skill.json';
import undefined from './skills/Employ Logical Process for General Assumption of Truth.skill.json';
import undefined from './skills/Premise and Conclusion Linking.skill.json';
import undefined from './skills/Limited Environment Financial Accounting Role Identification.skill.json';
import undefined from './skills/Structured Environment Financial Accounting Role Identification.skill.json';
import undefined from './skills/Capital Budgeting Methods.skill.json';
import undefined from './skills/Working Capital Measurement.skill.json';
import undefined from './skills/Financial Tools and Techniques.skill.json';
import undefined from './skills/Improvement Opportunity Identification.skill.json';
import undefined from './skills/Novel Solution Identification.skill.json';
import undefined from './skills/Generally Accepted Accounting Principles Application.skill.json';
import undefined from './skills/General Corporate Accounting Procedure Implementation.skill.json';
import undefined from './skills/General Corporate Accounting Procedure Maintenance.skill.json';
import undefined from './skills/Generally Accepted Accounting Principles (GAAP) Methodology Review.skill.json';
import undefined from './skills/Generally Accepted Accounting Principles (GAAP) Methodology Implementation.skill.json';
import undefined from './skills/Generally Accepted Accounting Principles (GAAP) Methodology Enforcement.skill.json';
import undefined from './skills/Financial Statement Decision Making Review.skill.json';
import undefined from './skills/Financial Statement Decision Making Analysis.skill.json';
import undefined from './skills/Business Activity Conveyance.skill.json';
import undefined from './skills/Financial Transactions Recording.skill.json';
import undefined from './skills/Account Balance Integrity Verification.skill.json';
import undefined from './skills/Temporary Account Closing.skill.json';
import undefined from './skills/Data Set Ensurance.skill.json';
import undefined from './skills/Cash Inflow and Outflow Examination.skill.json';
import undefined from './skills/Financial Data Representation.skill.json';
import undefined from './skills/Accounting Method and Policy Implementation.skill.json';
import undefined from './skills/Accounting Method and Policy Enforcement.skill.json';
import undefined from './skills/Double-Entry Bookkeeping Method Record.skill.json';
import undefined from './skills/Analytical Goal Spreadsheet Modification.skill.json';
import undefined from './skills/Root Cause Analysis (RCA) Action Plan Development.skill.json';
import undefined from './skills/Software and Hardware Requirements Ensurance.skill.json';
import undefined from './skills/Business Operations Opportunities Identification.skill.json';

export { , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , ,  };