name: Update Collection

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Run Action to Update Collection
        uses: wgu-skills/updater@main
        with:
          skillCollectionUrl: 'https://osmt.wgu.edu/api/collections/1db79be3-ff33-4114-8449-e151aa9e6b25'
          patToken: ${{ secrets.GH_PAT}}